[[headers]]
for = "/_astro/*"
    [headers.values]
        Access-Control-Allow-Origin = "*"
        X-XSS-Protection = "1; mode=block"
        Cache-Control = "max-age=604800; immutable"

[[redirects]]
from = "/introduction"
to = "/getting-started/introduction"
